# Generated by Django 4.0 on 2021-12-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'model_log',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('strategy1', 'strategy1'), ('strategy2', 'strategy2'), ('strategy3', 'strategy3')], default='strategy1', max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('sell_share', models.IntegerField(default=0)),
                ('buy_share', models.IntegerField(default=0)),
                ('sell_stop_percentage', models.IntegerField(default=1)),
                ('buy_stop_percentage', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'model_stock',
            },
        ),
    ]
