# Generated by Django 4.0 on 2021-12-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'model_log',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('buy_share', models.IntegerField(default=0)),
                ('buy_stop_percentage', models.IntegerField(default=1)),
                ('sell_share', models.IntegerField(default=0)),
                ('sell_stop_percentage', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'model_stock',
            },
        ),
    ]
